name: Test

on:
  workflow_run:
    workflows: ["Install"]
    branches: ["main"]
    types: 
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add "codes" and "project_codes" folders to sys.path
        run: |
          echo 'import sys' >> $GITHUB_WORKSPACE/codes/project_codes/__init__.py
          echo 'sys.path.append("$GITHUB_WORKSPACE/codes/project_codes")' >> $GITHUB_WORKSPACE/codes/project_codes/__init__.py
        working-directory: ${{ github.workspace }}
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
    - name: install packages
      run: pip install -r requirements.txt
    - name: test
      run: make test
    - name: run python script to create outputs
      run: python codes/test_codes/test_script.py
    - name: Archive and Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml_pipeline-artifacts
        path: ${{ github.workspace }}
        
    - name: Save to repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo GH_TOKEN: "${GH_TOKEN}"
        git config --global user.name 'github-actions'
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Add results"
        git push
